import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { id: 'uz', name: "O'zbekcha", flag: '🇺🇿', code: 'UZ' },
  { id: 'ru', name: 'Русский', flag: '🇷🇺', code: 'RU' },
  { id: 'en', name: 'English', flag: '🇬🇧', code: 'GB' },
  { id: 'kg', name: 'Кыргызча', flag: '🇰🇬', code: 'KG' },
  { id: 'kz', name: 'Қазақша', flag: '🇰🇿', code: 'KZ' },
  { id: 'af', name: 'دری', flag: '🇦🇫', code: 'AF' },
  { id: 'tj', name: 'Тоҷикӣ', flag: '🇹🇯', code: 'TJ' },
];

const translations = {
  uz: {
    home: 'Asosiy',
    search: 'Yaxshilik qidirish...',
    categories: 'Kategoriyalar',
    seeAll: 'Barchasi',
    freeDelivery: 'Bepul yetkazib berish',
    bannerText: 'Tabiiy mahsulotlar uyingizda',
    orderNow: 'Hozir buyurtma bering',
    featured: 'Saralangan mahsulotlar',
    noResults: 'Mahsulot topilmadi',
    cart: 'Savat',
    total: 'Jami',
    checkout: 'Rasmiylashtirish',
    profile: 'Profil',
    history: 'Buyurtmalar',
    saved: 'Saqlanganlar',
    settings: 'Sozlamalar',
    language: 'Til',
    addToCart: 'Savatga qoish',
    description: 'Tavsif',
    source: 'Manba',
    harvested: 'Yig’ilgan vaqti',
    // Categories
    cat_vegetables: 'Sabzavotlar',
    cat_fruits: 'Mevalar',
    cat_greens: 'Ko’katlar',
    // Products
    prod_spinach: 'Ismaloq',
    prod_bell_peppers: 'Bolgar qalampiri',
    prod_broccoli: 'Brokkoli',
    prod_carrots: 'Shirin sabzi',
    prod_potatoes: 'Kartoshka',
    prod_tomatoes: 'Pomidor',
    prod_apples: 'Qizil olma',
    // Units
    unit_bundle: 'bog’lam',
    unit_kg: 'kg',
    unit_head: 'dona',
    // Descriptions
    desc_spinach: 'Mahalliy sharoitda yetishtirilgan yangi organik ismaloq. Temir va vitaminlarga boy.',
    desc_bell_peppers: 'Qisirlovchi va shirin qizil qalampir. S vitamini manbai.',
    desc_broccoli: 'Zaharli dorilarsiz o’stirilgan yuqori sifatli brokkoli.',
    desc_carrots: 'Tabiiy shirin va qarsildoq sabzi. Beta-karotinga boy.',
    desc_potatoes: 'Har qanday ovqat uchun mos keladigan organik kartoshka.',
    desc_tomatoes: 'Sershira va pishgan pomidorlar. Salat va souslar uchun ideal.',
    desc_apples: 'Shirin va qarsildoq qizil olmalar. Sog’lom tamaddi uchun ajoyib.',
  },
  ru: {
    home: 'Главная',
    search: 'Поиск свежих продуктов...',
    categories: 'Категории',
    seeAll: 'Все',
    freeDelivery: 'Бесплатная доставка',
    bannerText: 'Органическая еда с доставкой',
    orderNow: 'Заказать сейчас',
    featured: 'Популярное',
    noResults: 'Ничего не найдено',
    cart: 'Корзина',
    total: 'Итого',
    checkout: 'Оформить заказ',
    profile: 'Профиль',
    history: 'Заказы',
    saved: 'Избранное',
    settings: 'Настройки',
    language: 'Язык',
    addToCart: 'В корзину',
    description: 'Описание',
    source: 'Источник',
    harvested: 'Собрано',
    // Categories
    cat_vegetables: 'Овощи',
    cat_fruits: 'Фрукты',
    cat_greens: 'Зелень',
    // Products
    prod_spinach: 'Шпинат',
    prod_bell_peppers: 'Болгарский перец',
    prod_broccoli: 'Брокколи',
    prod_carrots: 'Сладкая морковь',
    prod_potatoes: 'Картофель',
    prod_tomatoes: 'Помидоры',
    prod_apples: 'Красные яблоки',
    // Units
    unit_bundle: 'пучок',
    unit_kg: 'кг',
    unit_head: 'шт',
    // Descriptions
    desc_spinach: 'Свежий органический шпинат, выращенный местно. Богат железом и витаминами.',
    desc_bell_peppers: 'Хрустящий и сладкий красный перец. Высокое содержание витамина С.',
    desc_broccoli: 'Брокколи премиум-качества с плотными соцветиями. Без пестицидов.',
    desc_carrots: 'Натурально сладкая и хрустящая морковь. Богата бета-каротином.',
    desc_potatoes: 'Универсальный органический картофель. Свежесобранный с местных полей.',
    desc_tomatoes: 'Сочные и спелые томаты. Идеальны для соусов и салатов.',
    desc_apples: 'Сладкие и хрустящие красные яблоки. Идеально для перекуса.',
  },
  en: {
    home: 'Home',
    search: 'Search for fresh food...',
    categories: 'Categories',
    seeAll: 'See all',
    freeDelivery: 'Free Delivery',
    bannerText: 'Organic food delivered to your home',
    orderNow: 'Order Now',
    featured: 'Featured Fresh',
    noResults: 'No products found',
    cart: 'Cart',
    total: 'Total',
    checkout: 'Checkout',
    profile: 'Profile',
    history: 'Orders',
    saved: 'Saved',
    settings: 'Settings',
    language: 'Language',
    addToCart: 'Add to Cart',
    description: 'Description',
    source: 'Source',
    harvested: 'Harvested',
    // Categories
    cat_vegetables: 'Vegetables',
    cat_fruits: 'Fruits',
    cat_greens: 'Greens',
    // Products
    prod_spinach: 'Organic Spinach',
    prod_bell_peppers: 'Red Bell Peppers',
    prod_broccoli: 'Fresh Broccoli',
    prod_carrots: 'Sweet Carrots',
    prod_potatoes: 'Potatoes',
    prod_tomatoes: 'Tomatoes',
    prod_apples: 'Red Apples',
    // Units
    unit_bundle: 'bundle',
    unit_kg: 'kg',
    unit_head: 'head',
    // Descriptions
    desc_spinach: 'Fresh organic spinach harvested locally. Rich in iron and vitamins. Perfect for salads and smoothies.',
    desc_bell_peppers: 'Crispy and sweet red bell peppers. High in Vitamin C. Great for roasting or fresh salads.',
    desc_broccoli: 'Premium quality broccoli with dense green florets. Organically grown without pesticides.',
    desc_carrots: 'Naturally sweet and crunchy carrots. Rich in beta-carotene. Perfect for snacking or cooking.',
    desc_potatoes: 'Versatile organic potatoes. Perfect for mashing, roasting, or boiling. Freshly dug from local soil.',
    desc_tomatoes: 'Juicy and ripe vine tomatoes. Bursting with flavor. Ideal for sauces, salads, and sandwiches.',
    desc_apples: 'Sweet and crunchy organic red apples. Perfect for a healthy snack or baking.',
  },
  kg: {
    home: 'Башкы',
    search: 'Таттуу тамак издөө...',
    categories: 'Категориялар',
    seeAll: 'Баары',
    freeDelivery: 'Акысыз жеткирүү',
    bannerText: 'Органикалык тамак үйүңүзгө',
    orderNow: 'Азыр заказ кыл',
    featured: 'Тандалган',
    noResults: 'Эч нерсе табылган жок',
    cart: 'Себет',
    total: 'Жалпы',
    checkout: 'Оформите заказ',
    profile: 'Профиль',
    history: 'Буйрутмалар',
    saved: 'Сакталган',
    settings: 'Жөндөөлөр',
    language: 'Тил',
    addToCart: 'Себетке кошуу',
    description: 'Сүрөттөмө',
    source: 'Булак',
    harvested: 'Жыйналган убактысы',
    // Categories
    cat_vegetables: 'Жашылчалар',
    cat_fruits: 'Мөмө-жемиштер',
    cat_greens: 'Көк чөптөр',
    // Products
    prod_spinach: 'Шпинат',
    prod_bell_peppers: 'Болгар калемпири',
    prod_broccoli: 'Брокколи',
    prod_carrots: 'Таттуу сабиз',
    prod_potatoes: 'Картошка',
    prod_tomatoes: 'Помидор',
    prod_apples: 'Кызыл алма',
    // Units
    unit_bundle: 'боо',
    unit_kg: 'кг',
    unit_head: 'даана',
    // Descriptions
    desc_spinach: 'Жергиликтүү өстүрүлгөн жаңы органикалык шпинат. Темир жана витаминдерге бай.',
    desc_bell_peppers: 'Кытырак жана таттуу кызыл калемпир. С витаминине бай.',
    desc_broccoli: 'Пестицидсиз өстүрүлгөн жогорку сапаттагы брокколи.',
    desc_carrots: 'Табигый таттуу жана кытырак сабиз. Бета-каротинге бай.',
    desc_potatoes: 'Ар кандай тамакка ылайыктуу органикалык картошка.',
    desc_tomatoes: 'Ширелүү жана бышкан помидорлор. Салаттар үчүн идеалдуу.',
    desc_apples: 'Таттуу жана кытырак кызыл алмалар. Ден соолукка пайдалуу.',
  },
  kz: {
    home: 'Басты',
    search: 'Балғын тағамды іздеу...',
    categories: 'Санаттар',
    seeAll: 'Барлығы',
    freeDelivery: 'Тегін жеткізу',
    bannerText: 'Органикалық тағам үйіңізде',
    orderNow: 'Қазір тапсырыс бер',
    featured: 'Таңдалған',
    noResults: 'Ештеңе табылмады',
    cart: 'Себет',
    total: 'Барлығы',
    checkout: 'Рәсімдеу',
    profile: 'Профиль',
    history: 'Тапсырыстар',
    saved: 'Сақталғандар',
    settings: 'Параметрлер',
    language: 'Тіл',
    addToCart: 'Себетке қосу',
    description: 'Сипаттама',
    source: 'Көз',
    harvested: 'Жиналған уақыты',
    // Categories
    cat_vegetables: 'Көкөністер',
    cat_fruits: 'Жемістер',
    cat_greens: 'Көк шөптер',
    // Products
    prod_spinach: 'Шпинат',
    prod_bell_peppers: 'Болгар бұрышы',
    prod_broccoli: 'Брокколи',
    prod_carrots: 'Тәтті сәбіз',
    prod_potatoes: 'Картоп',
    prod_tomatoes: 'Қызанақ',
    prod_apples: 'Қызыл алма',
    // Units
    unit_bundle: 'шоқ',
    unit_kg: 'кг',
    unit_head: 'дана',
    // Descriptions
    desc_spinach: 'Жергілікті жерде өсірілген жаңа органикалық шпинат. Темір мен дәрумендерге бай.',
    desc_bell_peppers: 'Қытырлақ және тәтті қызыл бұрыш. С дәруменіне бай.',
    desc_broccoli: 'Пестицидсіз өсірілген жоғары сапалы брокколи.',
    desc_carrots: 'Табиғи тәтті және қытырлақ сәбіз. Бета-каротинге бай.',
    desc_potatoes: 'Кез келген тағамға жарамды органикалық картоп.',
    desc_tomatoes: 'Шырынды және піскен қызанақтар. Салаттар үшін өте қолайлы.',
    desc_apples: 'Тәтті және қытырлақ қызыл алмалар. Дұрыс тамақтану үшін жақсы.',
  },
  af: {
    home: 'خانه',
    search: 'جستجوی غذای تازه...',
    categories: 'دسته بندی ها',
    seeAll: 'مشاهده همه',
    freeDelivery: 'ارسال رایگان',
    bannerText: 'غذای ارگانیک درب منزل شما',
    orderNow: 'سفارش دهید',
    featured: 'محصولات ویژه',
    noResults: 'محصولی یافت نشد',
    cart: 'سبد خرید',
    total: 'مجموع',
    checkout: 'پرداخت',
    profile: 'پروفایل',
    history: 'سفارشات',
    saved: 'ذخیره شده',
    settings: 'تنظیمات',
    language: 'زبان',
    addToCart: 'افزودن به سبد',
    description: 'توضیحات',
    source: 'منبع',
    harvested: 'زمان برداشت',
    // Categories
    cat_vegetables: 'سبزیجات',
    cat_fruits: 'میوه ها',
    cat_greens: 'سبزی ها',
    // Products
    prod_spinach: 'اسفناج',
    prod_bell_peppers: 'مرچ دولمه فیل',
    prod_broccoli: 'بروکلی',
    prod_carrots: 'زردک شیرین',
    prod_potatoes: 'کچالو',
    prod_tomatoes: 'بادنجان رومی',
    prod_apples: 'سیب سرخ',
    // Units
    unit_bundle: 'بسته',
    unit_kg: 'کیلو',
    unit_head: 'عدد',
    // Descriptions
    desc_spinach: 'اسفناج تازه ارگانیک محلی. سرشار از آهن و ویتامین.',
    desc_bell_peppers: 'مرچ دولمه فیل سرخ ترد و شیرین. دارای ویتامین سی بالا.',
    desc_broccoli: 'بروکلی با کیفیت عالی بدون مواد سمی.',
    desc_carrots: 'زردک شیرین و ترد طبیعی. سرشار از بتاکاروتن.',
    desc_potatoes: 'کچالو ارگانیک برای هر نوع پخت و پز.',
    desc_tomatoes: 'بادنجان رومی رسیده و آبدار. ایده آل برای سالاد و سوس.',
    desc_apples: 'سیب سرخ ترد و شیرین. میان وعده عالی و صحی.',
  },
  tj: {
    home: 'Асосӣ',
    search: 'Ҷустуҷӯи хӯроки тару тоза...',
    categories: 'Категорияҳо',
    seeAll: 'Ҳамааш',
    freeDelivery: 'Расонидани ройгон',
    bannerText: 'Хӯроки органикӣ ба хонаи шумо',
    orderNow: 'Ҳозир фармоиш диҳед',
    featured: 'Маҳсулоти интихобшуда',
    noResults: 'Ҳеҷ чиз ёфт нашуд',
    cart: 'Сабад',
    total: 'Ҷамъ',
    checkout: 'Бақайдгирӣ',
    profile: 'Профил',
    history: 'Фармоишҳо',
    saved: 'Захирашуда',
    settings: 'Танзимот',
    language: 'Забон',
    addToCart: 'Ба сабад',
    description: 'Тавсиф',
    source: 'Манбаъ',
    harvested: 'Вақти ҳосил',
    // Categories
    cat_vegetables: 'Сабзавот',
    cat_fruits: 'Меваҳо',
    cat_greens: 'Кабудӣ',
    // Products
    prod_spinach: 'Исмоноқ',
    prod_bell_peppers: 'Қаламфури булғорӣ',
    prod_broccoli: 'Брокколи',
    prod_carrots: 'Зардолуи ширин',
    prod_potatoes: 'Картошка',
    prod_tomatoes: 'Помидор',
    prod_apples: 'Себи сурх',
    // Units
    unit_bundle: 'даста',
    unit_kg: 'кг',
    unit_head: 'дона',
    // Descriptions
    desc_spinach: 'Исмоноқи тозаи органикӣ. Бо оҳан ва витаминҳо бой.',
    desc_bell_peppers: 'Қаламфури булғории сурх ва ширин. Манбаи витамини С.',
    desc_broccoli: 'Брокколи босифат бе заҳрхимикатҳо.',
    desc_carrots: 'Зардолуи табии ширин ва пахшшаванда. Бо бета-каротин бой.',
    desc_potatoes: 'Картошкаи органикӣ мувофиқ барои ҳар як хӯрок.',
    desc_tomatoes: 'Помидорҳои пухта ва сероб. Идеалӣ барои салат ва соусҳо.',
    desc_apples: 'Себҳои сурхи ширин ва пахшшаванда. Беҳтарин барои газакҳо.',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'uz');

  useEffect(() => {
    localStorage.setItem('lang', lang);
    document.dir = lang === 'af' ? 'rtl' : 'ltr';
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
